name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Generate CSV
        run: python gera_csv.py
        env:
          GITLAB_TOKEN: ${{ secrets.GITLABTOKEN }}

      - name: Prepare public folder
        run: |
          mkdir -p public
          cp index.html public/index.html
          cp issues_EPC.csv public/

      - name: Inject config.js
        run: |
          cat > public/config.js <<EOF
window.__API_CONFIG__ = {
  token: "${{ secrets.GITLABTOKEN }}",
  url: "https://gitlab.4mti.com.br",
  group: "94",
  milestone: "Cliente) Porto Seguro - EPC"
};
EOF

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: actions/deploy-pages@v4